[workspace]
resolver = "3"
members = ["crates/deskcam-proto", "crates/deskcam-source", "crates/deskcam"]

[workspace.package]
edition = "2024"
version = "0.1.0"
license = "MIT"

[workspace.dependencies]
windows = "0.62.2"
windows-core = "0.62.2"
deskcam-proto = { path = "crates/deskcam-proto" }

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1

[profile.dev]
panic = "abort"
