[package]
name = "deskcam-source"
description = "Media Foundation virtual camera source loaded by the Windows Camera Frame Server"
edition.workspace = true
version.workspace = true
license.workspace = true

[lib]
name = "deskcam_source"
crate-type = ["cdylib", "rlib"]

[dependencies]
deskcam-proto.workspace = true
windows-core.workspace = true

[dependencies.windows]
workspace = true
features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_Com_StructuredStorage",
    "Win32_System_Variant",
    "Win32_Media_MediaFoundation",
    "Win32_Media_KernelStreaming",
    "Win32_System_Registry",
    "Win32_System_LibraryLoader",
    "Win32_System_SystemServices",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_Threading",
]
